#ifndef MCPIX_H
#define MCPIX_H

/* Generated by cbindgen — DO NOT EDIT. Run `cargo xtask gen-bindings` to refresh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

enum McpixStatus
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    MCPIX_STATUS_OK = 0,
    MCPIX_STATUS_INVALID_ARGUMENT = 1,
    MCPIX_STATUS_TRANSPORT_FIELD_LENGTH = 2,
    MCPIX_STATUS_TRANSPORT_FIELD_CHARSET = 3,
    MCPIX_STATUS_TRANSPORT_FIELD_PREFIX = 4,
    MCPIX_STATUS_SEED_ID_LENGTH = 5,
    MCPIX_STATUS_SEED_ID_CHARSET = 6,
    MCPIX_STATUS_SEED_LENGTH = 7,
    MCPIX_STATUS_COUNTER_OVERFLOW = 8,
    MCPIX_STATUS_UNKNOWN_SEED = 9,
    MCPIX_STATUS_NO_RETAINED_RECEIPT = 10,
    MCPIX_STATUS_REPLAY_REJECTED = 11,
    MCPIX_STATUS_MISMATCH = 12,
    MCPIX_STATUS_STORAGE = 13,
    MCPIX_STATUS_TRANSPORT = 14,
    MCPIX_STATUS_UNSUPPORTED_PROTOCOL_VERSION = 15,
    MCPIX_STATUS_PANIC = 98,
    MCPIX_STATUS_UNKNOWN = 99,
};
#ifndef __cplusplus
typedef int32_t McpixStatus;
#endif // __cplusplus

/**
 * Handle opaco devolvido por `mcpix_receiver_new`. Tratá-lo como tipo
 * alheio do lado nativo — apenas passar e liberar.
 */
typedef struct {
    uint8_t _private[0];
} McpixReceiver;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Libera o handle. No-op se `handle` for nulo.
 *
 * # Safety
 * `handle` deve ter sido produzido por `mcpix_receiver_new` e não pode ter
 * sido liberado anteriormente.
 */
void mcpix_receiver_free(McpixReceiver *handle);

/**
 * Gera uma cobrança. Em sucesso, devolve o campo de transporte público em
 * `*out_field` (deve ser liberado com `mcpix_string_free`) e o contador
 * usado em `*out_counter`.
 *
 * # Safety
 * Todos os ponteiros devem ser válidos. `seed_id` UTF-8 terminado em null.
 */
McpixStatus mcpix_receiver_generate_charge(McpixReceiver *handle,
                                           const char *seed_id,
                                           uint64_t amount_cents,
                                           char **out_field,
                                           uint64_t *out_counter);

/**
 * Cria um novo `ReceiverSdk` com store/contador/RNG default (in-memory + OS).
 *
 * Versões futuras receberão delegates injetáveis (HttpTransport, SeedStore
 * custom) seguindo o padrão da seção 3 da especificação.
 *
 * # Safety
 * `out_handle` precisa apontar para um `*mut McpixReceiver` válido.
 */
McpixStatus mcpix_receiver_new(McpixReceiver **out_handle);

/**
 * Registra um recebedor. `seed_id` é UTF-8 terminado em null.
 *
 * # Safety
 * `handle` deve ser válido. `seed_id` deve apontar para C-string UTF-8.
 */
McpixStatus mcpix_receiver_register(McpixReceiver *handle, const char *seed_id);

/**
 * Valida um C₂ apresentado. Em sucesso, escreve o resultado em `*out_result`.
 *
 * # Safety
 * Todos os ponteiros devem ser válidos. `seed_id` e `presented_c2` em UTF-8.
 */
McpixStatus mcpix_receiver_validate(McpixReceiver *handle,
                                    const char *seed_id,
                                    uint64_t counter,
                                    const char *presented_c2,
                                    int32_t *out_result);

/**
 * Libera uma string previamente alocada por esta FFI.
 *
 * # Safety
 * `ptr` precisa ter sido devolvido por uma função desta crate. Passar `null`
 * é seguro (no-op).
 */
void mcpix_string_free(char *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MCPIX_H */
